services:
  - type: web
    name: whisper-app
    env: python
    plan: starter
    buildCommand: "apt-get update && apt-get install -y ffmpeg"
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
